services:
  - type: web
    name: just-chat
    runtime: elixir
    plan: free
    region: frankfurt
    buildCommand: ./build.sh
    startCommand: mix phx.server
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PORT
        value: 10000
      - key: MIX_ENV
        value: prod